version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: SMARTLIBRARIAN_DB
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: smartlibrarian
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/DB_Settings.sql