version: '3.8'

services:
  backend:
    image: 'liorlakhmann/backend-slp:1.1.1'
    build:
      context: .
      dockerfile: Backend/Dockerfile
    container_name: BACKEND_SMARTLIBRARIAN
    ports:
      - "8070:8070"
    depends_on:
      - db-backend
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/smartlibrarian
  frontend:
    image: 'liorlakhmann/frontend-slp:0.0.1'
    build:
      context: .
      dockerfile: Frontend/Dockerfile
    container_name: FRONTEND_SMARTLIBRARIAN
    ports:
      - "8080:8080"
  db-backend:
    image: postgres:latest
    container_name: SMARTLIBRARIAN_DB
    restart: always
    environment:
      POSTGRES_DB: smartlibrarian
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
