CREATE TABLE readers
(
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR                       NOT NULL UNIQUE,
    year_of_birth INT CHECK (year_of_birth > 1900) NOT NULL
);

CREATE TABLE books
(
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR                         NOT NULL UNIQUE,
    author          VARCHAR                         NOT NULL,
    year_of_publish INT CHECK (year_of_publish > 0) NOT NULL,
    reader_id       INT                             REFERENCES readers (id) ON DELETE SET NULL,
    taken_at        TIMESTAMP
);

INSERT INTO books (name, author, year_of_publish)
VALUES ('Frankenstein', 'Mary Shelley', 1818),
       ('Emma', 'Jane Austen', 1815),
       ('Les Misérables', 'Victor Hugo', 1862),
       ('Wuthering Heights', 'Emily Bronte', 1847),
       ('The Count of Monte Cristo', 'Alexandre Dumas', 1845),
       ('Great Expectations', 'Charles Dickens', 1861),
       ('The Picture of Dorian Gray', 'Oscar Wilde', 1890),
       ('Dracula', 'Bram Stoker', 1897),
       ('The Time Machine', 'H.G. Wells', 1895),
       ('The Catcher in the Rye', 'J.D. Salinger', 1951),
       ('Lord of the Flies', 'William Golding', 1954),
       ('To Kill a Mockingbird', 'Harper Lee', 1960),
       ('One Hundred Years of Solitude', 'Gabriel Garcia Marquez', 1967),
       ('Slaughterhouse-Five', 'Kurt Vonnegut', 1969),
       ('The Hitchhiker''s Guide to the Galaxy', 'Douglas Adams', 1979),
       ('The Name of the Rose', 'Umberto Eco', 1980),
       ('The Handmaid''s Tale', 'Margaret Atwood', 1985),
       ('The God of Small Things', 'Arundhati Roy', 1997),
       ('The Kite Runner', 'Khaled Hosseini', 2003),
       ('The Da Vinci Code', 'Dan Brown', 2003),
       ('The Girl with the Dragon Tattoo', 'Stieg Larsson', 2005),
       ('The Road', 'Cormac McCarthy', 2006),
       ('The Hunger Games', 'Suzanne Collins', 2008),
       ('The Help', 'Kathryn Stockett', 2009),
       ('The Nightingale', 'Kristin Hannah', 2015);

INSERT INTO readers (name, year_of_birth)
VALUES ('Ethan Nguyen', '1985'),
       ('Naomi Patel', '1996'),
       ('Amber Wells', '1972'),
       ('Lucas Grant', '1952'),
       ('Chloe Cooper', '1992'),
       ('Oscar Richardson', '1938'),
       ('Zoe Foster', '1983'),
       ('Evan Kim', '1976'),
       ('Olivia Hunter', '2002'),
       ('Max Harrison', '1969'),
       ('Lily Rodriguez', '1989'),
       ('Leo Collins', '1957'),
       ('Ava Ortiz', '1995'),
       ('Sofia Nguyen', '1978'),
       ('Isaac Reed', '1946');