CREATE TABLE roles
(
    id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL UNIQUE
);

CREATE TABLE users
(
    id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR NOT NULL UNIQUE,
    password VARCHAR NOT NULL,
    role_id  INT REFERENCES roles (id) ON DELETE SET NULL
);

-- CREATE TABLE users_roles
-- (
--     user_id INT REFERENCES users (id) ON DELETE SET NULL ,
--     role_id INT REFERENCES roles (id) ON DELETE SET NULL
-- );

INSERT INTO roles (name)
VALUES ('USER'),
       ('ADMIN');

INSERT INTO users (username, password, role_id)
VALUES ('user@test.com', '$2y$10$R1B5qshp/expAdEM2O8Z..m.4GcJCo/H.n2n8xxHX7drcCKYFrXt6', 1),
       ('admin@test.com', '$2y$10$IGUdGyzJpY2PcSP6lHd8LeL1UU353j9GFbAO6HOWZw.kiMALDeBqS', 2);

-- INSERT INTO users_roles (user_id, role_id)
-- VALUES (1, 1),
--        (2, 2);
