# Data Source Configuration
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/smartlibrarian
    username: postgres
    password: postgres

# Hibernate Configuration
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  # PUT, PATCH, DELETE
  mvc:
    hiddenmethod:
      filter:
        enabled: true