server:
  port: 8060

# Data Source Configuration
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5442/smartlibrariansec
    username: postgres
    password: postgres
    hikari:
      leak-detection-threshold: 60000
      maximum-pool-size: 20

  # Hibernate Configuration
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: off

  # PUT, PATCH, DELETE
  mvc:
    hiddenmethod:
      filter:
        enabled: true

# Swagger Configuration
springdoc:
  api-docs:
    path: "/api-docs"
  swagger-ui:
    path: "/swagger.html"